export const kanjiDatabase = {
    grade1: [
        {kanji: '山道', reading: 'やまみち', meaning: '山の中の道'},
        {kanji: '川辺', reading: 'かわべ', meaning: '川のほとり'},
        {kanji: '花畑', reading: 'はなばたけ', meaning: '花がたくさん咲く畑'},
        {kanji: '草原', reading: 'そうげん', meaning: '草が広がる原っぱ'},
        {kanji: '青空', reading: 'あおぞら', meaning: '青い空'},
        {kanji: '森', reading: 'もり', meaning: '木がたくさん集まった場所'},
        {kanji: '池水', reading: 'いけみず', meaning: '池の水'},
        {kanji: '竹林', reading: 'ちくりん', meaning: '竹が生えた林'},
        {kanji: '雪原', reading: 'せつげん', meaning: '雪が積もった広い野原'},
        {kanji: '月見', reading: 'つきみ', meaning: '月を眺めること'},
        {kanji: '火山', reading: 'かざん', meaning: '溶岩が噴き出す山'},
        {kanji: '水田', reading: 'すいでん', meaning: '水を張った田んぼ'},
        {kanji: '大木', reading: 'たいぼく', meaning: '大きな木'},
        {kanji: '日光', reading: 'にっこう', meaning: '太陽の光'},
        {kanji: '小川', reading: 'おがわ', meaning: '小さな川'},
        {kanji: '川原', reading: 'かわら', meaning: '川の砂や石の浅瀬'},
        {kanji: '田畑', reading: 'たはた', meaning: '田んぼと畑'},
        {kanji: '木陰', reading: 'こかげ', meaning: '木の影になった涼しい場所'},
        {kanji: '月夜', reading: 'つきよ', meaning: '月が明るく照らす夜'},
        {kanji: '花火', reading: 'はなび', meaning: '空に打ち上げる光の花'},
        {kanji: '朝顔', reading: 'あさがお', meaning: '夏に朝咲く青紫の花'},
        {kanji: '金魚', reading: 'きんぎょ', meaning: '赤や金色の観賞用の魚'},
        {kanji: '虫取り', reading: 'むしとり', meaning: '虫を捕まえる遊び'},
        {kanji: '砂場', reading: 'すなば', meaning: '砂で遊ぶ公園の場所'},
        {kanji: '石橋', reading: 'いしばし', meaning: '石でできた橋'},
        {kanji: '木登り', reading: 'きのぼり', meaning: '木に登る遊び'},
        {kanji: '花束', reading: 'はなたば', meaning: '花をまとめた束'},
        {kanji: '落葉', reading: 'おちば', meaning: '木から落ちた葉'},
        {kanji: '風車', reading: 'かざぐるま', meaning: '風で回る玩具'},
        {kanji: '雪だるま', reading: 'ゆきだるま', meaning: '雪を丸めて作る人形'},
        {kanji: '水遊び', reading: 'みずあそび', meaning: '水で遊ぶこと'},
        {kanji: '虫眼鏡', reading: 'むしめがね', meaning: '小さいものを大きく見るレンズ'},
        {kanji: '花壇', reading: 'かだん', meaning: '花を植えた区画'},
        {kanji: '木の実', reading: 'きのみ', meaning: '木になる実・どんぐりなど'},
        {kanji: '石ころ', reading: 'いしころ', meaning: '小さな石'},
        {kanji: '葉っぱ', reading: 'はっぱ', meaning: '植物の葉'},
        {kanji: '雲海', reading: 'うんかい', meaning: '雲が海のように広がる景色'},
        {kanji: '夕立', reading: 'ゆうだち', meaning: '夕方に突然降る雨'},
        {kanji: '朝露', reading: 'あさつゆ', meaning: '朝に草につく水滴'},
        {kanji: '野原', reading: 'のはら', meaning: '広い草原・野っ原'},
        {kanji: '青虫', reading: 'あおむし', meaning: '緑色のイモ虫'},
        {kanji: '水たまり', reading: 'みずたまり', meaning: '雨水がたまった場所'},
        {kanji: '花びら', reading: 'はなびら', meaning: '花の一枚一枚のひらひら'},
        {kanji: '木漏れ日', reading: 'こもれび', meaning: '木の葉の間から差す光'},
        {kanji: '石段', reading: 'いしだん', meaning: '石でできた階段'},
        {kanji: '草むら', reading: 'くさむら', meaning: '草が茂った場所'},
        {kanji: '夕焼け雲', reading: 'ゆうやけぐも', meaning: '夕焼けで赤く染まった雲'},
        {kanji: '朝日', reading: 'あさひ', meaning: '朝に昇る太陽'},
        {kanji: '野いちご', reading: 'のいちご', meaning: '野山に自生するイチゴ'},
        {kanji: '落ち葉', reading: 'おちば', meaning: '木から落ちた葉っぱ'},
    ],
    grade2: [
        {kanji: '学校', reading: 'がっこう', meaning: '勉強する場所'},
        {kanji: '教室', reading: 'きょうしつ', meaning: '授業を受ける部屋'},
        {kanji: '先生', reading: 'せんせい', meaning: '教えてくれる人'},
        {kanji: '友達', reading: 'ともだち', meaning: '仲よしの人'},
        {kanji: '家族', reading: 'かぞく', meaning: 'いっしょに暮らす身内'},
        {kanji: '運動', reading: 'うんどう', meaning: '体を動かすこと'},
        {kanji: '朝食', reading: 'ちょうしょく', meaning: '朝ごはん'},
        {kanji: '昼食', reading: 'ちゅうしょく', meaning: 'お昼ごはん'},
        {kanji: '夕食', reading: 'ゆうしょく', meaning: '夕ごはん'},
        {kanji: '体育', reading: 'たいいく', meaning: '体を鍛える授業'},
        {kanji: '音楽', reading: 'おんがく', meaning: '歌や楽器の授業'},
        {kanji: '図工', reading: 'ずこう', meaning: '絵や工作の授業'},
        {kanji: '作文', reading: 'さくぶん', meaning: '文章を書くこと'},
        {kanji: '読書', reading: 'どくしょ', meaning: '本を読むこと'},
        {kanji: '遠足', reading: 'えんそく', meaning: '学校の校外見学旅行'},
        {kanji: '運動場', reading: 'うんどうじょう', meaning: '外で体を動かす校庭'},
        {kanji: '図書館', reading: 'としょかん', meaning: '本を読んだり借りる施設'},
        {kanji: '教科書', reading: 'きょうかしょ', meaning: '授業で使う本'},
        {kanji: '黒板', reading: 'こくばん', meaning: 'チョークで書く黒い板'},
        {kanji: '給食', reading: 'きゅうしょく', meaning: '学校で出るお昼ごはん'},
        {kanji: '運動靴', reading: 'うんどうぐつ', meaning: '体育で履く靴'},
        {kanji: '連絡帳', reading: 'れんらくちょう', meaning: '学校と家庭をつなぐノート'},
        {kanji: '席順', reading: 'せきじゅん', meaning: '座席の並び順'},
        {kanji: '掃除用具', reading: 'そうじようぐ', meaning: '掃除に使う道具'},
        {kanji: '図書室', reading: 'としょしつ', meaning: '学校内の本の部屋'},
        {kanji: '校門', reading: 'こうもん', meaning: '学校の正面の門'},
        {kanji: '時間割', reading: 'じかんわり', meaning: '授業の時間の表'},
        {kanji: '学年集会', reading: 'がくねんしゅうかい', meaning: '学年全体の集まり'},
        {kanji: '遠足写真', reading: 'えんそくしゃしん', meaning: '遠足で撮った写真'},
        {kanji: '学級文庫', reading: 'がっきゅうぶんこ', meaning: 'クラスの本棚'},
        {kanji: '給食袋', reading: 'きゅうしょくぶくろ', meaning: '給食道具を入れる袋'},
        {kanji: '体育帽', reading: 'たいいくぼう', meaning: '体育で被る帽子'},
        {kanji: '名札', reading: 'なふだ', meaning: '名前を書いたバッジ'},
        {kanji: '上履き', reading: 'うわばき', meaning: '校内で履く靴'},
        {kanji: '下校', reading: 'げこう', meaning: '学校から家に帰ること'},
        {kanji: '登校', reading: 'とうこう', meaning: '学校へ行くこと'},
        {kanji: '学級会', reading: 'がっきゅうかい', meaning: 'クラスで話し合う会'},
        {kanji: '図書カード', reading: 'としょかーど', meaning: '本を借りるためのカード'},
        {kanji: '音読カード', reading: 'おんどくかーど', meaning: '音読を記録するカード'},
        {kanji: '学級目標', reading: 'がっきゅうもくひょう', meaning: 'クラスの目標'},
        {kanji: '給食記録', reading: 'きゅうしょくきろく', meaning: '給食の記録'},
        {kanji: '体育館履き', reading: 'たいいくかんばき', meaning: '体育館専用の靴'},
        {kanji: '名札ケース', reading: 'なふだけーす', meaning: '名札を入れるケース'},
        {kanji: '下足箱', reading: 'げそくばこ', meaning: '靴を入れる箱'},
        {kanji: '登校班', reading: 'とうこうはん', meaning: '一緒に登校するグループ'},
        {kanji: '学級旗', reading: 'がっきゅうき', meaning: 'クラスの旗'},
        {kanji: '図書当番', reading: 'としょとうばん', meaning: '図書室の当番'},
        {kanji: '音楽発表', reading: 'おんがくはっぴょう', meaning: '音楽の発表会'},
        {kanji: '遠足弁当', reading: 'えんそくべんとう', meaning: '遠足に持っていくお弁当'},
    ],
    grade3: [
        {kanji: '運動会', reading: 'うんどうかい', meaning: 'sports day'},
        {kanji: '図画工作', reading: 'ずがこうさく', meaning: 'arts and crafts'},
        {kanji: '社会科', reading: 'しゃかいか', meaning: 'social studies'},
        {kanji: '理科室', reading: 'りかしつ', meaning: 'science room'},
        {kanji: '音楽会', reading: 'おんがくかい', meaning: 'music concert'},
        {kanji: '体育館', reading: 'たいいくかん', meaning: 'gymnasium'},
        {kanji: '給食当番', reading: 'きゅうしょくとうばん', meaning: 'lunch duty'},
        {kanji: '読書感想', reading: 'どくしょかんそう', meaning: 'book report'},
        {kanji: '遠足日記', reading: 'えんそくにっき', meaning: 'excursion diary'},
        {kanji: '学級会', reading: 'がっきゅうかい', meaning: 'class meeting'},
        {kanji: '自由研究', reading: 'じゆうけんきゅう', meaning: 'independent research'},
        {kanji: '社会見学', reading: 'しゃかいけんがく', meaning: 'field trip'},
        {kanji: '理科実験', reading: 'りかじっけん', meaning: 'science experiment'},
        {kanji: '音楽発表', reading: 'おんがくはっぴょう', meaning: 'music presentation'},
        {kanji: '委員会', reading: 'いいんかい', meaning: 'committee'},
        {kanji: '発表会', reading: 'はっぴょうかい', meaning: 'presentation'},
        {kanji: '学芸会', reading: 'がくげいかい', meaning: 'school arts festival'},
        {kanji: '図書委員', reading: 'としょいいん', meaning: 'library committee member'},
        {kanji: '学級新聞', reading: 'がっきゅうしんぶん', meaning: 'class newspaper'},
        {kanji: '係活動', reading: 'かかりかつどう', meaning: 'committee activity'},
        {kanji: '係決め', reading: 'かかりきめ', meaning: 'role assignment'},
        {kanji: '自由帳', reading: 'じゆうちょう', meaning: 'free notebook'},
        {kanji: '音読', reading: 'おんどく', meaning: 'reading aloud'},
        {kanji: '学習発表', reading: 'がくしゅうはっぴょう', meaning: 'learning presentation'},
        {kanji: '連絡網', reading: 'れんらくもう', meaning: 'contact network'},
        {kanji: '図書係', reading: 'としょがかり', meaning: 'library staff'},
        {kanji: '朝会', reading: 'ちょうかい', meaning: 'morning assembly'},
        {kanji: '放課後', reading: 'ほうかご', meaning: 'after school'},
        {kanji: '学級目標', reading: 'がっきゅうもくひょう', meaning: 'class goal'},
        {kanji: '遠足計画', reading: 'えんそくけいかく', meaning: 'excursion plan'},
        {kanji: '社会見学先', reading: 'しゃかいけんがくさき', meaning: 'field trip destination'},
        {kanji: '理科観察日記', reading: 'りかかんさつにっき', meaning: 'science observation diary'},
        {kanji: '係ノート', reading: 'かかりのーと', meaning: 'role notebook'},
        {kanji: '発表原稿', reading: 'はっぴょうげんこう', meaning: 'presentation script'},
        {kanji: '図書室利用', reading: 'としょしつりよう', meaning: 'library use'},
        {kanji: '学級旗', reading: 'がっきゅうき', meaning: 'class flag'},
        {kanji: '給食記録', reading: 'きゅうしょくきろく', meaning: 'lunch record'},
        {kanji: '自由研究展', reading: 'じゆうけんきゅうてん', meaning: 'independent research exhibition'},
        {kanji: '運動会練習', reading: 'うんどうかいれんしゅう', meaning: 'sports day practice'},
        {kanji: '遠足準備', reading: 'えんそくじゅんび', meaning: 'excursion preparation'},
        {kanji: '係活動記録', reading: 'かかりかつどうきろく', meaning: 'role activity record'},
        {kanji: '学級討論', reading: 'がっきゅうとうろん', meaning: 'class debate'},
        {kanji: '自由帳記入', reading: 'じゆうちょうきにゅう', meaning: 'free notebook entry'},
        {kanji: '発表会場', reading: 'はっぴょうかいじょう', meaning: 'presentation venue'},
        {kanji: '図書室整頓', reading: 'としょしつせいとん', meaning: 'library tidying'},
        {kanji: '学級会議', reading: 'がっきゅうかいぎ', meaning: 'class meeting'},
        {kanji: '給食当番表', reading: 'きゅうしょくとうばんひょう', meaning: 'lunch duty chart'},
        {kanji: '運動会旗', reading: 'うんどうかいき', meaning: 'sports day flag'},
        {kanji: '遠足感想', reading: 'えんそくかんそう', meaning: 'excursion impression'},
        {kanji: '理科観察会', reading: 'りかかんさつかい', meaning: 'science observation meeting'},
    ],
    grade4: [
        {kanji: '理科室', reading: 'りかしつ', meaning: 'science room'},
        {kanji: '音楽会', reading: 'おんがくかい', meaning: 'music concert'},
        {kanji: '体育館', reading: 'たいいくかん', meaning: 'gymnasium'},
        {kanji: '委員会', reading: 'いいんかい', meaning: 'committee'},
        {kanji: '図書館', reading: 'としょかん', meaning: 'library'},
        {kanji: '運動場', reading: 'うんどうじょう', meaning: 'playground'},
        {kanji: '社会見学', reading: 'しゃかいけんがく', meaning: 'field trip'},
        {kanji: '発表会', reading: 'はっぴょうかい', meaning: 'presentation'},
        {kanji: '学芸会', reading: 'がくげいかい', meaning: 'school arts festival'},
        {kanji: '社会科', reading: 'しゃかいか', meaning: 'social studies'},
        {kanji: '家庭科', reading: 'かていか', meaning: 'home economics'},
        {kanji: '算数科', reading: 'さんすうか', meaning: 'arithmetic'},
        {kanji: '学級会', reading: 'がっきゅうかい', meaning: 'class meeting'},
        {kanji: '読書感想', reading: 'どくしょかんそう', meaning: 'book report'},
        {kanji: '理科実験', reading: 'りかじっけん', meaning: 'science experiment'},
        {kanji: '音楽発表', reading: 'おんがくはっぴょう', meaning: 'music presentation'},
        {kanji: '委員長', reading: 'いいんちょう', meaning: 'committee chair'},
        {kanji: '社会調査', reading: 'しゃかいちょうさ', meaning: 'social survey'},
        {kanji: '理科観察', reading: 'りかかんさつ', meaning: 'science observation'},
        {kanji: '家庭訪問', reading: 'かていほうもん', meaning: 'home visit'},
        {kanji: '委員活動', reading: 'いいんかつどう', meaning: 'committee activity'},
        {kanji: '発表資料', reading: 'はっぴょうしりょう', meaning: 'presentation material'},
        {kanji: '読書週間', reading: 'どくしょしゅうかん', meaning: 'reading week'},
        {kanji: '社会調査', reading: 'しゃかいちょうさ', meaning: 'social survey'},
        {kanji: '理科観察', reading: 'りかかんさつ', meaning: 'science observation'},
        {kanji: '音楽発表会', reading: 'おんがくはっぴょうかい', meaning: 'music presentation event'},
        {kanji: '家庭訪問', reading: 'かていほうもん', meaning: 'home visit'},
        {kanji: '学級新聞', reading: 'がっきゅうしんぶん', meaning: 'class newspaper'},
        {kanji: '算数大会', reading: 'さんすうたいかい', meaning: 'arithmetic contest'},
        {kanji: '理科実験室', reading: 'りかじっけんしつ', meaning: 'science lab'},
        {kanji: '委員会活動', reading: 'いいんかいかつどう', meaning: 'committee activities'},
        {kanji: '発表練習', reading: 'はっぴょうれんしゅう', meaning: 'presentation practice'},
        {kanji: '社会科見学', reading: 'しゃかいかけんがく', meaning: 'social studies field trip'},
        {kanji: '理科実験記録', reading: 'りかじっけんきろく', meaning: 'science experiment record'},
        {kanji: '家庭科実習', reading: 'かていかじっしゅう', meaning: 'home economics practice'},
        {kanji: '算数プリント', reading: 'さんすうぷりんと', meaning: 'arithmetic worksheet'},
        {kanji: '音楽鑑賞', reading: 'おんがくかんしょう', meaning: 'music appreciation'},
        {kanji: '学級新聞作成', reading: 'がっきゅうしんぶんさくせい', meaning: 'class newspaper making'},
        {kanji: '読書感想会', reading: 'どくしょかんそうかい', meaning: 'book report meeting'},
        {kanji: '遠足感想文', reading: 'えんそくかんそうぶん', meaning: 'excursion essay'},
        {kanji: '委員長会議', reading: 'いいんちょうかいぎ', meaning: 'committee chair meeting'},
        {kanji: '発表会場', reading: 'はっぴょうかいじょう', meaning: 'presentation venue'},
        {kanji: '社会科新聞', reading: 'しゃかいかしんぶん', meaning: 'social studies newspaper'},
        {kanji: '理科自由研究', reading: 'りかじゆうけんきゅう', meaning: 'science independent research'},
        {kanji: '音楽会練習', reading: 'おんがくかいれんしゅう', meaning: 'music concert practice'},
        {kanji: '家庭科作品', reading: 'かていかさくひん', meaning: 'home economics work'},
        {kanji: '学級討論', reading: 'がっきゅうとうろん', meaning: 'class debate'},
        {kanji: '読書感想発表', reading: 'どくしょかんそうはっぴょう', meaning: 'book report presentation'},
        {kanji: '遠足準備', reading: 'えんそくじゅんび', meaning: 'excursion preparation'},
    ],
    grade5: [
        {kanji: '家庭科', reading: 'かていか', meaning: 'home economics'},
        {kanji: '算数科', reading: 'さんすうか', meaning: 'arithmetic'},
        {kanji: '委員会', reading: 'いいんかい', meaning: 'committee'},
        {kanji: '卒業式', reading: 'そつぎょうしき', meaning: 'graduation ceremony'},
        {kanji: '修学旅行', reading: 'しゅうがくりょこう', meaning: 'school trip'},
        {kanji: '学級会', reading: 'がっきゅうかい', meaning: 'class meeting'},
        {kanji: '読書感想', reading: 'どくしょかんそう', meaning: 'book report'},
        {kanji: '社会科', reading: 'しゃかいか', meaning: 'social studies'},
        {kanji: '理科実験', reading: 'りかじっけん', meaning: 'science experiment'},
        {kanji: '音楽発表', reading: 'おんがくはっぴょう', meaning: 'music presentation'},
        {kanji: '自由研究', reading: 'じゆうけんきゅう', meaning: 'independent research'},
        {kanji: '社会見学', reading: 'しゃかいけんがく', meaning: 'field trip'},
        {kanji: '卒業証書', reading: 'そつぎょうしょうしょ', meaning: 'diploma'},
        {kanji: '修了証書', reading: 'しゅうりょうしょうしょ', meaning: 'certificate of completion'},
        {kanji: '卒業文集', reading: 'そつぎょうぶんしゅう', meaning: 'graduation essays'},
        {kanji: '学年主任', reading: 'がくねんしゅにん', meaning: 'grade leader'},
        {kanji: '委員長', reading: 'いいんちょう', meaning: 'committee chair'},
        {kanji: '学芸会', reading: 'がくげいかい', meaning: 'school arts festival'},
        {kanji: '発表会', reading: 'はっぴょうかい', meaning: 'presentation'},
        {kanji: '図書委員', reading: 'としょいいん', meaning: 'library committee member'},
        {kanji: '卒業研究', reading: 'そつぎょうけんきゅう', meaning: 'graduation research'},
        {kanji: '学年集会', reading: 'がくねんしゅうかい', meaning: 'grade meeting'},
        {kanji: '委員長会', reading: 'いいんちょうかい', meaning: 'committee chair meeting'},
        {kanji: '発表準備', reading: 'はっぴょうじゅんび', meaning: 'presentation preparation'},
        {kanji: '社会見学記', reading: 'しゃかいけんがくき', meaning: 'field trip report'},
        {kanji: '理科観察記', reading: 'りかかんさつき', meaning: 'science observation report'},
        {kanji: '音楽発表会', reading: 'おんがくはっぴょうかい', meaning: 'music presentation event'},
        {kanji: '家庭訪問記', reading: 'かていほうもんき', meaning: 'home visit report'},
        {kanji: '学級目標', reading: 'がっきゅうもくひょう', meaning: 'class goal'},
        {kanji: '読書感想文', reading: 'どくしょかんそうぶん', meaning: 'book report essay'},
        {kanji: '卒業文集編集', reading: 'そつぎょうぶんしゅうへんしゅう', meaning: 'graduation essay editing'},
        {kanji: '学年目標', reading: 'がくねんもくひょう', meaning: 'grade goal'},
        {kanji: '委員長発表', reading: 'いいんちょうはっぴょう', meaning: 'committee chair presentation'},
        {kanji: '発表会準備', reading: 'はっぴょうかいじゅんび', meaning: 'presentation preparation'},
        {kanji: '社会科新聞', reading: 'しゃかいかしんぶん', meaning: 'social studies newspaper'},
        {kanji: '理科自由研究', reading: 'りかじゆうけんきゅう', meaning: 'science independent research'},
        {kanji: '音楽会練習', reading: 'おんがくかいれんしゅう', meaning: 'music concert practice'},
        {kanji: '家庭科作品', reading: 'かていかさくひん', meaning: 'home economics work'},
        {kanji: '学級討論', reading: 'がっきゅうとうろん', meaning: 'class debate'},
        {kanji: '読書感想発表', reading: 'どくしょかんそうはっぴょう', meaning: 'book report presentation'},
        {kanji: '遠足感想', reading: 'えんそくかんそう', meaning: 'excursion impression'},
        {kanji: '理科観察会', reading: 'りかかんさつかい', meaning: 'science observation meeting'},
    ],
    grade6: [
        {kanji: '卒業式', reading: 'そつぎょうしき', meaning: 'graduation ceremony'},
        {kanji: '修学旅行', reading: 'しゅうがくりょこう', meaning: 'school trip'},
        {kanji: '学級会', reading: 'がっきゅうかい', meaning: 'class meeting'},
        {kanji: '生徒会', reading: 'せいとかい', meaning: 'student council'},
        {kanji: '部活動', reading: 'ぶかつどう', meaning: 'club activities'},
        {kanji: '卒業文集', reading: 'そつぎょうぶんしゅう', meaning: 'graduation essays'},
        {kanji: '委員長', reading: 'いいんちょう', meaning: 'committee chair'},
        {kanji: '学年主任', reading: 'がくねんしゅにん', meaning: 'grade leader'},
        {kanji: '卒業証書', reading: 'そつぎょうしょうしょ', meaning: 'diploma'},
        {kanji: '修了証書', reading: 'しゅうりょうしょうしょ', meaning: 'certificate of completion'},
        {kanji: '自由研究', reading: 'じゆうけんきゅう', meaning: 'independent research'},
        {kanji: '社会見学', reading: 'しゃかいけんがく', meaning: 'field trip'},
        {kanji: '理科実験', reading: 'りかじっけん', meaning: 'science experiment'},
        {kanji: '音楽発表', reading: 'おんがくはっぴょう', meaning: 'music presentation'},
        {kanji: '卒業旅行', reading: 'そつぎょうりょこう', meaning: 'graduation trip'},
        {kanji: '学芸会', reading: 'がくげいかい', meaning: 'school arts festival'},
        {kanji: '発表会', reading: 'はっぴょうかい', meaning: 'presentation'},
        {kanji: '図書委員', reading: 'としょいいん', meaning: 'library committee member'},
        {kanji: '進路指導', reading: 'しんろしどう', meaning: 'career guidance'},
        {kanji: '卒業旅行記', reading: 'そつぎょうりょこうき', meaning: 'graduation trip report'},
        {kanji: '進路希望', reading: 'しんろきぼう', meaning: 'career hope'},
        {kanji: '生徒総会', reading: 'せいとそうかい', meaning: 'student general meeting'},
        {kanji: '部活動報告', reading: 'ぶかつどうほうこく', meaning: 'club activity report'},
        {kanji: '卒業証書授与', reading: 'そつぎょうしょうしょじゅよ', meaning: 'diploma awarding'},
        {kanji: '修了証書授与', reading: 'しゅうりょうしょうしょじゅよ', meaning: 'certificate awarding'},
        {kanji: '卒業文集作成', reading: 'そつぎょうぶんしゅうさくせい', meaning: 'graduation essay making'},
        {kanji: '学年主任会', reading: 'がくねんしゅにんかい', meaning: 'grade leader meeting'},
        {kanji: '委員長発表', reading: 'いいんちょうはっぴょう', meaning: 'committee chair presentation'},
        {kanji: '進路相談', reading: 'しんろそうだん', meaning: 'career counseling'},
        {kanji: '卒業式準備', reading: 'そつぎょうしきじゅんび', meaning: 'graduation ceremony preparation'},
        {kanji: '進路面談', reading: 'しんろめんだん', meaning: 'career interview'},
        {kanji: '生徒会選挙', reading: 'せいとかいせんきょ', meaning: 'student council election'},
        {kanji: '部活動大会', reading: 'ぶかつどうたいかい', meaning: 'club activity tournament'},
        {kanji: '卒業証書作成', reading: 'そつぎょうしょうしょさくせい', meaning: 'diploma making'},
        {kanji: '修了証書作成', reading: 'しゅうりょうしょうしょさくせい', meaning: 'certificate making'},
        {kanji: '卒業文集朗読', reading: 'そつぎょうぶんしゅうろうどく', meaning: 'graduation essay reading'},
        {kanji: '学年主任発表', reading: 'がくねんしゅにんはっぴょう', meaning: 'grade leader presentation'},
        {kanji: '委員長会議', reading: 'いいんちょうかいぎ', meaning: 'committee chair meeting'},
        {kanji: '進路説明会', reading: 'しんろせつめいかい', meaning: 'career guidance meeting'},
        {kanji: '卒業式練習', reading: 'そつぎょうしきれんしゅう', meaning: 'graduation ceremony practice'},
        {kanji: '学年主任会', reading: 'がくねんしゅにんかい', meaning: 'grade leader meeting'},
        {kanji: '委員活動報告', reading: 'いいんかつどうほうこく', meaning: 'committee activity report'},
        {kanji: '発表原稿', reading: 'はっぴょうげんこう', meaning: 'presentation script'},
        {kanji: '社会見学先', reading: 'しゃかいけんがくさき', meaning: 'field trip destination'},
        {kanji: '理科観察日記', reading: 'りかかんさつにっき', meaning: 'science observation diary'},
        {kanji: '音楽発表会', reading: 'おんがくはっぴょうかい', meaning: 'music presentation event'},
        {kanji: '家庭訪問記', reading: 'かていほうもんき', meaning: 'home visit report'},
        {kanji: '学級新聞作成', reading: 'がっきゅうしんぶんさくせい', meaning: 'class newspaper making'},
        {kanji: '読書週間', reading: 'どくしょしゅうかん', meaning: 'reading week'},
    ],
    middle: [
        {kanji: '生徒会', reading: 'せいとかい', meaning: 'student council'},
        {kanji: '部活動', reading: 'ぶかつどう', meaning: 'club activities'},
        {kanji: '英語科', reading: 'えいごか', meaning: 'English department'},
        {kanji: '数学科', reading: 'すうがくか', meaning: 'mathematics department'},
        {kanji: '理科実験', reading: 'りかじっけん', meaning: 'science experiment'},
        {kanji: '社会科', reading: 'しゃかいか', meaning: 'social studies'},
        {kanji: '卒業式', reading: 'そつぎょうしき', meaning: 'graduation ceremony'},
        {kanji: '修学旅行', reading: 'しゅうがくりょこう', meaning: 'school trip'},
        {kanji: '学級会', reading: 'がっきゅうかい', meaning: 'class meeting'},
        {kanji: '委員会', reading: 'いいんかい', meaning: 'committee'},
        {kanji: '文化祭', reading: 'ぶんかさい', meaning: 'school festival'},
        {kanji: '体育祭', reading: 'たいいくさい', meaning: 'sports festival'},
        {kanji: '合唱祭', reading: 'がっしょうさい', meaning: 'choral festival'},
        {kanji: '卒業証書', reading: 'そつぎょうしょうしょ', meaning: 'diploma'},
        {kanji: '修了証書', reading: 'しゅうりょうしょうしょ', meaning: 'certificate of completion'},
        {kanji: '卒業文集', reading: 'そつぎょうぶんしゅう', meaning: 'graduation essays'},
        {kanji: '学年主任', reading: 'がくねんしゅにん', meaning: 'grade leader'},
        {kanji: '委員長', reading: 'いいんちょう', meaning: 'committee chair'},
        {kanji: '学芸会', reading: 'がくげいかい', meaning: 'school arts festival'},
        {kanji: '発表会', reading: 'はっぴょうかい', meaning: 'presentation'},
        {kanji: '生徒手帳', reading: 'せいとてちょう', meaning: 'student handbook'},
        {kanji: '学級委員', reading: 'がっきゅういいん', meaning: 'class committee'},
        {kanji: '部活動計画', reading: 'ぶかつどうけいかく', meaning: 'club activity plan'},
        {kanji: '文化講演', reading: 'ぶんかこうえん', meaning: 'cultural lecture'},
        {kanji: '進路指導室', reading: 'しんろしどうしつ', meaning: 'career guidance room'},
        {kanji: '学年集会', reading: 'がくねんしゅうかい', meaning: 'grade meeting'},
        {kanji: '委員活動報告', reading: 'いいんかつどうほうこく', meaning: 'committee activity report'},
        {kanji: '卒業研究発表', reading: 'そつぎょうけんきゅうはっぴょう', meaning: 'graduation research presentation'},
        {kanji: '理科観察記録', reading: 'りかかんさつきろく', meaning: 'science observation record'},
        {kanji: '社会調査報告', reading: 'しゃかいちょうさほうこく', meaning: 'social survey report'},
        {kanji: '生徒会活動', reading: 'せいとかいかつどう', meaning: 'student council activity'},
        {kanji: '部活動発表', reading: 'ぶかつどうはっぴょう', meaning: 'club activity presentation'},
        {kanji: '英語スピーチ', reading: 'えいごすぴーち', meaning: 'English speech'},
        {kanji: '数学検定', reading: 'すうがくけんてい', meaning: 'math certification'},
        {kanji: '理科観察会', reading: 'りかかんさつかい', meaning: 'science observation meeting'},
        {kanji: '社会科発表', reading: 'しゃかいかはっぴょう', meaning: 'social studies presentation'},
        {kanji: '卒業式練習', reading: 'そつぎょうしきれんしゅう', meaning: 'graduation ceremony practice'},
        {kanji: '修学旅行記', reading: 'しゅうがくりょこうき', meaning: 'school trip report'},
        {kanji: '学級会議', reading: 'がっきゅうかいぎ', meaning: 'class meeting'},
        {kanji: '委員会報告', reading: 'いいんかいほうこく', meaning: 'committee report'},
        {kanji: '生徒会選挙', reading: 'せいとかいせんきょ', meaning: 'student council election'},
        {kanji: '部活動大会', reading: 'ぶかつどうたいかい', meaning: 'club activity tournament'},
        {kanji: '英語検定', reading: 'えいごけんてい', meaning: 'English certification'},
        {kanji: '数学大会', reading: 'すうがくたいかい', meaning: 'math contest'},
        {kanji: '理科自由研究', reading: 'りかじゆうけんきゅう', meaning: 'science independent research'},
        {kanji: '社会科新聞', reading: 'しゃかいかしんぶん', meaning: 'social studies newspaper'},
        {kanji: '卒業式準備', reading: 'そつぎょうしきじゅんび', meaning: 'graduation ceremony preparation'},
        {kanji: '修学旅行準備', reading: 'しゅうがくりょこうじゅんび', meaning: 'school trip preparation'},
        {kanji: '学級討論', reading: 'がっきゅうとうろん', meaning: 'class debate'},
        {kanji: '委員会活動', reading: 'いいんかいかつどう', meaning: 'committee activities'},
    ],
    common: [
        {kanji: '経済学', reading: 'けいざいがく', meaning: 'economics'},
        {kanji: '情報処理', reading: 'じょうほうしょり', meaning: 'information processing'},
        {kanji: '国際化', reading: 'こくさいか', meaning: 'internationalization'},
        {kanji: '環境問題', reading: 'かんきょうもんだい', meaning: 'environmental problem'},
        {kanji: '少子化', reading: 'しょうしか', meaning: 'declining birthrate'},
        {kanji: '高齢化', reading: 'こうれいか', meaning: 'aging population'},
        {kanji: '人工知能', reading: 'じんこうちのう', meaning: 'artificial intelligence'},
        {kanji: '情報社会', reading: 'じょうほうしゃかい', meaning: 'information society'},
        {kanji: '国際交流', reading: 'こくさいこうりゅう', meaning: 'international exchange'},
        {kanji: '科学技術', reading: 'かがくぎじゅつ', meaning: 'science and technology'},
        {kanji: '新幹線', reading: 'しんかんせん', meaning: 'bullet train'},
        {kanji: '携帯電話', reading: 'けいたいでんわ', meaning: 'mobile phone'},
        {kanji: '電子辞書', reading: 'でんしじしょ', meaning: 'electronic dictionary'},
        {kanji: '自動販売', reading: 'じどうはんばい', meaning: 'vending'},
        {kanji: '高速道路', reading: 'こうそくどうろ', meaning: 'expressway'},
        {kanji: '国際空港', reading: 'こくさいくうこう', meaning: 'international airport'},
        {kanji: '情報通信', reading: 'じょうほうつうしん', meaning: 'information communication'},
        {kanji: '経済成長', reading: 'けいざいせいちょう', meaning: 'economic growth'},
        {kanji: '社会保障', reading: 'しゃかいほしょう', meaning: 'social security'},
        {kanji: '国民健康', reading: 'こくみんけんこう', meaning: 'national health'},
        {kanji: '情報管理', reading: 'じょうほうかんり', meaning: 'information management'},
        {kanji: '経済政策', reading: 'けいざいせいさく', meaning: 'economic policy'},
        {kanji: '社会問題', reading: 'しゃかいもんだい', meaning: 'social problem'},
        {kanji: '国際協力', reading: 'こくさいきょうりょく', meaning: 'international cooperation'},
        {kanji: '環境保護', reading: 'かんきょうほご', meaning: 'environmental protection'},
        {kanji: '情報公開', reading: 'じょうほうこうかい', meaning: 'information disclosure'},
        {kanji: '経済活動', reading: 'けいざいかつどう', meaning: 'economic activity'},
        {kanji: '社会福祉', reading: 'しゃかいふくし', meaning: 'social welfare'},
        {kanji: '国民投票', reading: 'こくみんとうひょう', meaning: 'national referendum'},
        {kanji: '科学研究', reading: 'かがくけんきゅう', meaning: 'scientific research'},
        {kanji: '情報産業', reading: 'じょうほうさんぎょう', meaning: 'information industry'},
        {kanji: '経済連携', reading: 'けいざいれんけい', meaning: 'economic partnership'},
        {kanji: '社会運動', reading: 'しゃかいうんどう', meaning: 'social movement'},
        {kanji: '国際条約', reading: 'こくさいじょうやく', meaning: 'international treaty'},
        {kanji: '環境政策', reading: 'かんきょうせいさく', meaning: 'environmental policy'},
        {kanji: '情報革命', reading: 'じょうほうかくめい', meaning: 'information revolution'},
        {kanji: '経済危機', reading: 'けいざいきき', meaning: 'economic crisis'},
        {kanji: '社会構造', reading: 'しゃかいこうぞう', meaning: 'social structure'},
        {kanji: '国民運動', reading: 'こくみんうんどう', meaning: 'national movement'},
        {kanji: '科学論文', reading: 'かがくろんぶん', meaning: 'scientific paper'},
        {kanji: '情報通信網', reading: 'じょうほうつうしんもう', meaning: 'information network'},
        {kanji: '経済発展', reading: 'けいざいはってん', meaning: 'economic development'},
        {kanji: '社会資本', reading: 'しゃかいしほん', meaning: 'social capital'},
        {kanji: '国際貿易', reading: 'こくさいぼうえき', meaning: 'international trade'},
        {kanji: '環境基準', reading: 'かんきょうきじゅん', meaning: 'environmental standard'},
        {kanji: '情報公開法', reading: 'じょうほうこうかいほう', meaning: 'information disclosure law'},
        {kanji: '経済指標', reading: 'けいざいしひょう', meaning: 'economic indicator'},
        {kanji: '社会保障費', reading: 'しゃかいほしょうひ', meaning: 'social security cost'},
        {kanji: '国民年金', reading: 'こくみんねんきん', meaning: 'national pension'},
        {kanji: '科学技術賞', reading: 'かがくぎじゅつしょう', meaning: 'science and technology award'},
    ],
    nando: [
        {kanji: '海月', reading: 'くらげ', meaning: 'jellyfish'},
        {kanji: '木菟', reading: 'みみずく', meaning: 'horned owl'},
        {kanji: '山茶花', reading: 'さざんか', meaning: 'sasanqua camellia'},
        {kanji: '石榴', reading: 'ざくろ', meaning: 'pomegranate'},
        {kanji: '杜若', reading: 'かきつばた', meaning: 'iris'},
        {kanji: '海豹', reading: 'あざらし', meaning: 'seal'},
        {kanji: '鰐梨', reading: 'アボカド', meaning: 'avocado'},
        {kanji: '海豚', reading: 'いるか', meaning: 'dolphin'},
        {kanji: '蒲公英', reading: 'たんぽぽ', meaning: 'dandelion'},
        {kanji: '向日葵', reading: 'ひまわり', meaning: 'sunflower'},
        {kanji: '秋桜', reading: 'こすもす', meaning: 'cosmos'},
        {kanji: '蓬莱', reading: 'ほうらい', meaning: 'paradise'},
        {kanji: '金糸雀', reading: 'かなりあ', meaning: 'canary'},
        {kanji: '時雨', reading: 'しぐれ', meaning: 'drizzle'},
        {kanji: '白粉花', reading: 'おしろいばな', meaning: 'four oclock flower'},
        {kanji: '鈴蘭', reading: 'すずらん', meaning: 'lily of the valley'},
        {kanji: '躑躅', reading: 'つつじ', meaning: 'azalea'},
        {kanji: '忍冬', reading: 'すいかずら', meaning: 'honeysuckle'},
        {kanji: '風信子', reading: 'ひやしんす', meaning: 'hyacinth'},
        {kanji: '紫陽花', reading: 'あじさい', meaning: 'hydrangea'},
        {kanji: '檸檬', reading: 'れもん', meaning: 'lemon'},
        {kanji: '躑躅', reading: 'つつじ', meaning: 'azalea'},
        {kanji: '薔薇', reading: 'ばら', meaning: 'rose'},
        {kanji: '鬱金香', reading: 'うこんこう', meaning: 'tulip'},
        {kanji: '竜胆', reading: 'りんどう', meaning: 'gentian'},
        {kanji: '梔子', reading: 'くちなし', meaning: 'gardenia'},
        {kanji: '杜鵑', reading: 'ほととぎす', meaning: 'cuckoo'},
        {kanji: '鶏冠', reading: 'とさか', meaning: 'rooster comb'},
        {kanji: '鶏頭', reading: 'けいとう', meaning: 'cockscomb'},
        {kanji: '曙草', reading: 'あけぼのそう', meaning: 'primrose'},
        {kanji: '鬼灯', reading: 'ほおずき', meaning: 'ground cherry'},
        {kanji: '紫蘇', reading: 'しそ', meaning: 'perilla'},
        {kanji: '菖蒲', reading: 'しょうぶ', meaning: 'iris'},
        {kanji: '梵天', reading: 'ぼんてん', meaning: 'bonten'},
        {kanji: '山椒', reading: 'さんしょう', meaning: 'Japanese pepper'},
        {kanji: '白樺', reading: 'しらかば', meaning: 'white birch'},
        {kanji: '柚子', reading: 'ゆず', meaning: 'yuzu'},
        {kanji: '竜舌蘭', reading: 'りゅうぜつらん', meaning: 'agave'},
        {kanji: '鬼百合', reading: 'おにゆり', meaning: 'tiger lily'},
    ],
    chonando: [
        {kanji: '鸚哥', reading: 'いんこ', meaning: 'parakeet'},
        {kanji: '鸛', reading: 'こうのとり', meaning: 'stork'},
        {kanji: '鸞', reading: 'らん', meaning: 'phoenix'},
        {kanji: '馴鹿', reading: 'となかい', meaning: 'reindeer'},
        {kanji: '犀', reading: 'さい', meaning: 'rhinoceros'},
        {kanji: '羚羊', reading: 'かもしか', meaning: 'serow'},
        {kanji: '麒麟', reading: 'きりん', meaning: 'giraffe'},
        {kanji: '鴛鴦', reading: 'おしどり', meaning: 'mandarin duck'},
        {kanji: '鸚鵡', reading: 'おうむ', meaning: 'parrot'},
        {kanji: '鶺鴒', reading: 'せきれい', meaning: 'wagtail'},
        {kanji: '鶉', reading: 'うずら', meaning: 'quail'},
        {kanji: '鷦鷯', reading: 'みそさざい', meaning: 'wren'},
        {kanji: '鷲', reading: 'わし', meaning: 'eagle'},
        {kanji: '鷹', reading: 'たか', meaning: 'hawk'},
        {kanji: '鵯', reading: 'ひよどり', meaning: 'bulbul'},
        {kanji: '鵲', reading: 'かささぎ', meaning: 'magpie'},
        {kanji: '鶚', reading: 'みさご', meaning: 'osprey'},
        {kanji: '鶲', reading: 'ひたき', meaning: 'redstart'},
        {kanji: '鶫', reading: 'つぐみ', meaning: 'thrush'},
        {kanji: '鶯', reading: 'うぐいす', meaning: 'bush warbler'},
        {kanji: '鷗', reading: 'かもめ', meaning: 'seagull'},
        {kanji: '鷲', reading: 'わし', meaning: 'eagle'},
        {kanji: '鷹', reading: 'たか', meaning: 'hawk'},
        {kanji: '鵲', reading: 'かささぎ', meaning: 'magpie'},
        {kanji: '鵯', reading: 'ひよどり', meaning: 'brown-eared bulbul'},
        {kanji: '鵡', reading: 'むくどり', meaning: 'starling'},
        {kanji: '鵞鳥', reading: 'がちょう', meaning: 'goose'},
        {kanji: '鵬', reading: 'ほう', meaning: 'roc (mythical bird)'},
        {kanji: '鶉', reading: 'うずら', meaning: 'quail'},
        {kanji: '鶩', reading: 'あひる', meaning: 'domestic duck'},
        {kanji: '鶚', reading: 'みさご', meaning: 'osprey'},
        {kanji: '鰯雲', reading: 'いわしぐも', meaning: 'mackerel sky'},
        {kanji: '雲母', reading: 'きらら', meaning: 'mica'},
        {kanji: '鶏冠', reading: 'とさか', meaning: 'rooster comb'},
        {kanji: '杜若', reading: 'かきつばた', meaning: 'iris'},
        {kanji: '躑躅', reading: 'つつじ', meaning: 'azalea'},
        {kanji: '山葵', reading: 'わさび', meaning: 'wasabi'},
        {kanji: '梔子', reading: 'くちなし', meaning: 'gardenia'},
        {kanji: '竜胆', reading: 'りんどう', meaning: 'gentian'},
        {kanji: '蒲公英', reading: 'たんぽぽ', meaning: 'dandelion'},
        {kanji: '向日葵', reading: 'ひまわり', meaning: 'sunflower'},
        {kanji: '秋桜', reading: 'こすもす', meaning: 'cosmos'},
        {kanji: '石榴', reading: 'ざくろ', meaning: 'pomegranate'},
        {kanji: '金糸雀', reading: 'かなりあ', meaning: 'canary'},
        {kanji: '時雨', reading: 'しぐれ', meaning: 'drizzle'},
        {kanji: '白粉花', reading: 'おしろいばな', meaning: 'four oclock flower'},
        {kanji: '鈴蘭', reading: 'すずらん', meaning: 'lily of the valley'},
        {kanji: '薔薇', reading: 'ばら', meaning: 'rose'},
        {kanji: '鬱金香', reading: 'うこんこう', meaning: 'tulip'},
        {kanji: '鬼灯', reading: 'ほおずき', meaning: 'ground cherry'},
        {kanji: '紫蘇', reading: 'しそ', meaning: 'perilla'},
        {kanji: '菖蒲', reading: 'しょうぶ', meaning: 'iris'},
        {kanji: '梵天', reading: 'ぼんてん', meaning: 'bonten'},
        {kanji: '榊', reading: 'さかき', meaning: 'sakaki'},
        {kanji: '柘植', reading: 'つげ', meaning: 'boxwood'},
        {kanji: '榧', reading: 'かや', meaning: 'Japanese nutmeg-yew'},
        {kanji: '柚子', reading: 'ゆず', meaning: 'yuzu'},
        {kanji: '銀杏', reading: 'いちょう', meaning: 'ginkgo'},
        {kanji: '蓬', reading: 'よもぎ', meaning: 'mugwort'},
        {kanji: '蓮', reading: 'はす', meaning: 'lotus'},
        {kanji: '芥子', reading: 'けし', meaning: 'poppy'},
        {kanji: '菫', reading: 'すみれ', meaning: 'violet'},
        {kanji: '撫子', reading: 'なでしこ', meaning: 'pink (flower)'},
        {kanji: '杜松', reading: 'ねず', meaning: 'juniper'},
        {kanji: '柿', reading: 'かき', meaning: 'persimmon'},
        {kanji: '檸檬', reading: 'れもん', meaning: 'lemon'},
        {kanji: '檜', reading: 'ひのき', meaning: 'Japanese cypress'},
        {kanji: '樅', reading: 'もみ', meaning: 'fir'},
        {kanji: '樫', reading: 'かし', meaning: 'oak'},
        {kanji: '樟', reading: 'くす', meaning: 'camphor tree'},
        {kanji: '楓', reading: 'かえで', meaning: 'maple'},
        {kanji: '楠', reading: 'くすのき', meaning: 'camphor tree'},
        {kanji: '椋鳥', reading: 'むくどり', meaning: 'white-cheeked starling'},
        {kanji: '椿', reading: 'つばき', meaning: 'camellia'},
        {kanji: '槐', reading: 'えんじゅ', meaning: 'pagoda tree'},
        {kanji: '橙', reading: 'だいだい', meaning: 'bitter orange'},
        {kanji: '橡', reading: 'とち', meaning: 'horse chestnut'},
        {kanji: '檀', reading: 'まゆみ', meaning: 'spindle tree'},
        {kanji: '檜扇', reading: 'ひおうぎ', meaning: 'iris domestica'},
        {kanji: '竜舌蘭', reading: 'りゅうぜつらん', meaning: 'agave'},
        {kanji: '鬼百合', reading: 'おにゆり', meaning: 'tiger lily'},
    ]
}; 